name: C CI with cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make cppcheck

    - name: Run build
      run: make build

    - name: Run cppcheck
      run: make cppcheck

    - name: Show cppcheck results
      run: cat cppcheck.log || true
