name: C CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make clang-tidy

    - name: Build project
      run: make

    - name: Run clang-tidy
      run: clang-tidy src/*.c -- -I./src
